all:
	@clear
	@make -C ./ex00
	@make -C ./ex01
	@make -C ./ex02
	@clear
	@echo "all set"
	@read -p "Press Enter to continue..."
	@clear
	@echo "==============ex00=============="
	@./ex00/run
	@read -p "Press Enter to continue..."
	@clear
	@echo "==============ex01=============="
	@./ex01/run
	@read -p "Press Enter to continue..."
	@clear
	@echo "==============ex02=============="
	@./ex02/run

fclean:
	@clear
	make fclean -C ./ex00
	make fclean -C ./ex01
	make fclean -C ./ex02
	@clear
